import { TopicTemplate } from "@/components/TopicTemplate";
import { TopicFaqs } from "@/components/TopicFaqs";
import { CollapsibleSubsection } from "@/components/CollapsibleSubsection";
import { ExamSection } from "@/components/ExamSection";
import { WorkedExample } from "@/components/WorkedExamples";
import LaserFibreopticsDiagram from "@/components/diagrams/LaserFibreopticsDiagram";
import { laserFibreopticsQuiz } from "@/data/quizzes";
import { Exam } from "@/data/curriculum";
import { ExamPitfallsCallout } from "@/components/ExamPitfallsCallout";
import InlineRef from "@/components/InlineRef";

const laserFibreopticsFaqs: Array<[string, string]> = [
  [
    "What are the key safety measures for airway laser surgery?",
    "FiO₂ ≤30 %, avoid N₂O (supports combustion), use a laser-resistant ETT (red-rubber wrapped with metallic foil, or purpose-built Mallinckrodt Laser-Flex), saline-filled cuff with methylene blue indicator, eye protection for staff and patient (wavelength-specific goggles), warning signs on theatre doors, smoke evacuation, and immediate access to saline and a backup tube."
  ],
  [
    "What is the management of an airway fire?",
    "Stop ventilation and disconnect O₂. Remove the burning tube. Pour saline into the airway to extinguish. Re-mask ventilate on air. Re-intubate (often with a smaller tube), perform bronchoscopy to assess thermal injury, administer steroids and humidified O₂. Admit to critical care for observation of progressive airway oedema (peaks 12–24 h)."
  ],
  [
    "How does an optical fibre transmit light?",
    "Total internal reflection. The core (high refractive index) is surrounded by a cladding (lower refractive index). Light entering within the acceptance cone reflects off the core–cladding boundary at angles greater than the critical angle and propagates along the fibre with minimal loss. Bundles are coherent (image transmission — fibrescope) or non-coherent (light transmission only)."
  ]
];

const objectives = [
  "Define LASER and explain the requirement for population inversion in a gain medium",
  "Describe the three defining properties of laser light: monochromaticity, coherence and collimation",
  "Match common surgical lasers (CO₂, Nd:YAG, KTP) to their wavelengths, target chromophores and clinical applications",
  "Apply Snell's law and total internal reflection to explain image transmission through fibreoptic bundles (NA = √(n₁² − n₂²))",
  "Plan an anaesthetic for airway laser surgery, including FiO₂ minimisation, laser-safe ETT selection and eye protection",
];

const workedExamples: WorkedExample[] = [
  {
    title: "Airway fire risk during CO₂ laser laryngeal surgery",
    scenario:
      "A 55-year-old smoker is listed for CO₂ laser excision of a vocal cord papilloma. The surgeon asks for FiO₂ 0.4 with N₂O supplementation through a standard PVC microlaryngeal tube. What changes are required?",
    working:
      "CO₂ laser (10,600 nm) is fully absorbed by water → ignites PVC at low energies.\nFire triangle = oxidiser + fuel + ignition. PVC = fuel; CO₂ laser = ignition; O₂ ± N₂O = oxidiser (N₂O behaves as an oxidiser at temperatures generated by the laser).\nKey mitigations (per the Association of Anaesthetists 2023 'Management of complications of airway management' guideline): laser-resistant (metal-bodied, e.g. Laser-Flex) ETT; lowest clinically appropriate FiO₂ — typically ≤ 0.30 in air, titrated to SpO₂ — with N₂O omitted; cuff filled with saline ± methylene blue; saline-soaked pledgets around the cuff; surgeon to use the lowest effective laser power; saline, a spare circuit and a bronchoscope immediately to hand.",
    answer:
      "Decline the original plan. Use a laser-resistant ETT, deliver the lowest FiO₂ that maintains adequate SpO₂ (commonly ≤ 0.30) with N₂O omitted, fill the cuff with saline + dye, and follow the Association of Anaesthetists 2023 airway-fire drill if ignition occurs: simultaneously stop airway gases and remove the burning tracheal tube, extinguish the fire with saline, then re-establish ventilation with air (titrating FiO₂ up only as needed), re-intubate and perform bronchoscopy to assess thermal/inhalational injury.",
    cites: ["Middleton Ch.14", "Assoc Anaesth Airway Fire"],
  },
  {
    title: "Numerical aperture of a fibreoptic bronchoscope",
    scenario:
      "A coherent fibre bundle uses a glass core (n₁ = 1.62) and cladding (n₂ = 1.52). Calculate the numerical aperture and the maximum acceptance half-angle in air.",
    working:
      "NA = √(n₁² − n₂²) = √(1.62² − 1.52²) = √(2.6244 − 2.3104) = √0.314 ≈ 0.56.\nNA = n₀ sin θ_max with n₀ (air) = 1 → sin θ_max = 0.56 → θ_max ≈ 34°.\nCritical angle inside the fibre: sin θc = n₂/n₁ = 1.52/1.62 = 0.938 → θc ≈ 69.8° (measured from the normal).",
    answer:
      "NA ≈ 0.56, giving an acceptance half-angle of ~34° in air. Light entering within this cone undergoes total internal reflection (above the 69.8° critical angle) and propagates with negligible loss along the fibre.",
    cites: ["Cross & Plunkett Ch.18"],
  },
];

const LaserFibreopticsTopic = () => {
  return (
    <TopicTemplate
      title="Lasers & Fibreoptics"
      subtitle="LASER principles, fibreoptic light transmission, total internal reflection, and clinical applications"
      backPath="/physics"
      backLabel="Physics"
      accentColor="text-physics"
      topicId="lasers-fibreoptics"
      topicTitle="Lasers & Fibreoptics"
      objectives={objectives}
      workedExamples={workedExamples}
      quizQuestions={laserFibreopticsQuiz}
      sectionExamMapping={{
        objectives: { exams: [Exam.PRIMARY, Exam.FINAL], curriculumCodes: ["RCoA Primary — Physics", "RCoA Final — Physics"] },
        workedExamples: { exams: [Exam.PRIMARY, Exam.FINAL] },
        keyPoints: { exams: [Exam.PRIMARY, Exam.FINAL] },
      }}
      sectionSources={{
        workedExamples: ["BJA Educ 2017", "Middleton Ch.14", "Cross & Plunkett Ch.18", "Assoc Anaesth Airway Fire"],
        keyPoints: ["BJA Educ 2017", "Middleton Ch.14", "Cross & Plunkett Ch.18", "BJA Educ 2004", "Assoc Anaesth Airway Fire"],
      }}
      keyPoints={[
        { text: "LASER = Light Amplification by Stimulated Emission of Radiation — requires population inversion in a gain medium", cites: ["BJA Educ 2004"] },
        { text: "Laser light is monochromatic (single wavelength), coherent (waves in phase), and collimated (parallel beam)", cites: ["Middleton Ch.14"] },
        { text: "CO₂ laser (10,600 nm) is absorbed by water and cuts tissue; it ignites PVC ETTs — use laser-safe tubes with saline-filled cuffs", cites: ["Cross & Plunkett Ch.18"] },
        { text: "Total internal reflection occurs when light travels from high to low refractive index at angle > critical angle (sin θc = n₂/n₁)", cites: ["BJA Educ 2004"] },
        { text: "Coherent fibre bundles transmit images (fibres maintain spatial position); incoherent bundles transmit light only", cites: ["Middleton Ch.14"] },
        { text: "Numerical aperture NA = √(n₁² − n₂²) defines the acceptance cone angle of the fibre", cites: ["Cross & Plunkett Ch.18"] },
        { text: "Use the lowest clinically appropriate FiO₂ (typically ≤30%) during airway laser surgery and avoid N₂O — per current Association of Anaesthetists / DAS shared-airway guidance and the published airway-fire algorithm", cites: ["Assoc Anaesth Airway Fire"] },
      ]}
      coreConcepts={
        <>
          <ExamSection id="introduction" exams={[Exam.PRIMARY, Exam.FINAL]}>
            <CollapsibleSubsection title="Introduction" defaultOpen>
            <p className="text-muted-foreground leading-relaxed">
              Lasers and fibreoptics are fundamental to modern anaesthetic and surgical practice. Understanding laser physics is
              essential for safe airway laser surgery, while fibreoptic principles underpin the fibreoptic bronchoscope — a
              cornerstone of difficult airway management. Both topics appear regularly in the Primary FRCA physics examination.
            </p>
            </CollapsibleSubsection>
          </ExamSection>

          <ExamSection id="diagram" exams={[Exam.PRIMARY, Exam.FINAL]}>
            <CollapsibleSubsection title="Interactive Diagrams">
            <LaserFibreopticsDiagram />
            </CollapsibleSubsection>
          </ExamSection>

          <ExamSection id="laser-physics" exams={[Exam.PRIMARY, Exam.FINAL]}>
            <CollapsibleSubsection title="LASER Physics">
            <div className="text-muted-foreground leading-relaxed space-y-3">
              <p>
                A laser produces light through <strong>stimulated emission</strong>. An incoming photon interacts with an atom in an
                excited (metastable) state, causing it to emit an identical photon — same wavelength, phase, and direction. This
                requires <strong>population inversion</strong>: more atoms must be in the excited state than the ground state, achieved
                by external energy input (pumping) — optical, electrical, or chemical.
              </p>
              <p>
                The gain medium sits within an <strong>optical cavity</strong> bounded by two mirrors. The total mirror reflects all
                light back; the partial mirror allows a fraction to escape as the laser beam. Multiple passes through the gain medium
                amplify the light exponentially. The resulting beam is <strong>monochromatic</strong> (single wavelength),
                <strong> coherent</strong> (waves in phase), and <strong>collimated</strong> (parallel, minimal divergence).
              </p>
              <p>
                <strong>CO₂ laser</strong> (10,600 nm, far infrared): strongly absorbed by water → precise cutting and vaporisation.
                Used extensively in airway surgery. <strong>Nd:YAG</strong> (1,064 nm, near infrared): penetrates deeply into tissue,
                good for coagulation. Can be transmitted via fibreoptic. <strong>KTP</strong> (532 nm, green): frequency-doubled
                Nd:YAG, absorbed by haemoglobin, used for superficial vascular lesions and vocal cord surgery.
              </p>
            </div>
            </CollapsibleSubsection>
          </ExamSection>

          <ExamSection id="fibreoptics" exams={[Exam.PRIMARY, Exam.FINAL]}>
            <CollapsibleSubsection title="Fibreoptics & Total Internal Reflection">
            <div className="text-muted-foreground leading-relaxed space-y-3">
              <p>
                <strong>Total internal reflection (TIR)</strong> occurs when light travelling from a medium of higher refractive index
                (n₁, core) to one of lower refractive index (n₂, cladding) strikes the interface at an angle greater than the
                <strong> critical angle</strong>: sin θc = n₂/n₁. All light is reflected back into the core with zero transmission loss.
              </p>
              <p>
                The <strong>numerical aperture (NA)</strong> of a fibre defines the cone of light it can accept: NA = √(n₁² − n₂²).
                A larger NA accepts more light but provides lower image resolution. Clinical fibreoptic bundles contain thousands of
                individual fibres, each 8–12 μm in diameter.
              </p>
              <p>
                <strong>Coherent bundles</strong> maintain the spatial arrangement of fibres from one end to the other, allowing image
                transmission (viewing channel of bronchoscope). <strong>Incoherent bundles</strong> have random fibre arrangement and
                transmit light only (illumination channel). Modern video bronchoscopes use a CCD chip at the tip instead of a coherent
                bundle, providing superior image quality.
              </p>
            </div>
            </CollapsibleSubsection>
          </ExamSection>

          <ExamSection id="laser-safety" exams={[Exam.PRIMARY, Exam.FINAL]}>
            <CollapsibleSubsection title="Laser Safety in Anaesthesia">
            <div className="text-muted-foreground leading-relaxed space-y-3">
              <p>
                <strong>Airway fire</strong> is the most feared complication of airway laser surgery. The CO₂ laser can ignite
                standard PVC or rubber endotracheal tubes. Prevention — as set out in the Association of Anaesthetists 2023
                guideline <em>Management of complications of airway management</em>
                <InlineRef topicId="lasers-fibreoptics" refLabel="Assoc Anaesth Airway Fire" /> — requires: laser-resistant tubes (metal
                shaft, e.g. Laser-Flex); the <strong>lowest clinically appropriate FiO₂</strong>, titrated to SpO₂ (commonly
                ≤ 0.30 when tolerated); avoidance of N₂O (acts as an oxidiser at laser temperatures); a saline-filled cuff
                (± methylene blue as a leak indicator); and saline-soaked pledgets around the cuff. If ignition occurs, the
                guideline drill is: <strong>(1)</strong> simultaneously stop the airway gases and remove the burning tracheal
                tube; <strong>(2)</strong> extinguish the fire with saline; <strong>(3)</strong> re-establish ventilation with
                air, titrating FiO₂ upward only as needed; <strong>(4)</strong> re-intubate and perform bronchoscopy to assess
                thermal and inhalational injury.
              </p>
              <p>
                <strong>Eye protection</strong> is mandatory for all theatre personnel. The goggles must be specific to the laser
                wavelength in use (CO₂ goggles do not protect against Nd:YAG). The patient's eyes are taped shut and covered with wet
                gauze. Warning signs must be displayed on all theatre doors, and the laser should be key-operated with a designated
                laser safety officer.
              </p>
            </div>
            </CollapsibleSubsection>
          </ExamSection>
          <ExamPitfallsCallout
            accent="physics"
            pitfalls={[
              "LASER = Light Amplification by Stimulated Emission of Radiation — needs a population inversion in an active medium.",
              "CO₂ laser (10.6 µm) cuts and is absorbed by water; Nd:YAG (1.064 µm) penetrates deeper; KTP (532 nm) is absorbed by haemoglobin.",
              "Airway laser safety: FiO₂ <30%, no N₂O, laser-resistant tube, saline-filled cuff, wet swabs, eye protection for all in room.",
              "Class 4 lasers require controlled environment, warning signs, key-switch and a designated laser safety officer.",
              "Fibreoptics rely on total internal reflection within a higher-index core; coherent bundles transmit images, non-coherent bundles transmit light only.",
            ]}
          />
          <TopicFaqs faqs={laserFibreopticsFaqs} />

        </>
      }
    />
  );
};

export default LaserFibreopticsTopic;
