import { TopicTemplate } from "@/components/TopicTemplate";
import { ExamSection } from "@/components/ExamSection";
import { WorkedExample } from "@/components/WorkedExamples";
import LaserFibreopticsDiagram from "@/components/diagrams/LaserFibreopticsDiagram";
import { laserFibreopticsQuiz } from "@/data/quizzes";
import { Exam } from "@/data/curriculum";
import { ExamPitfallsCallout } from "@/components/ExamPitfallsCallout";

const objectives = [
  "Define LASER and explain the requirement for population inversion in a gain medium",
  "Describe the three defining properties of laser light: monochromaticity, coherence and collimation",
  "Match common surgical lasers (CO₂, Nd:YAG, KTP) to their wavelengths, target chromophores and clinical applications",
  "Apply Snell's law and total internal reflection to explain image transmission through fibreoptic bundles (NA = √(n₁² − n₂²))",
  "Plan an anaesthetic for airway laser surgery, including FiO₂ minimisation, laser-safe ETT selection and eye protection",
];

const workedExamples: WorkedExample[] = [
  {
    title: "Airway fire risk during CO₂ laser laryngeal surgery",
    scenario:
      "A 55-year-old smoker is listed for CO₂ laser excision of a vocal cord papilloma. The surgeon asks for FiO₂ 0.4 with N₂O supplementation through a standard PVC microlaryngeal tube. What changes are required?",
    working:
      "CO₂ laser (10,600 nm) is fully absorbed by water → ignites PVC at low energies.\nFire triangle = oxidiser + fuel + ignition. PVC = fuel; CO₂ laser = ignition; O₂ ± N₂O = oxidiser (N₂O behaves as an oxidiser at temperatures generated by the laser).\nKey mitigations: laser-safe (metal-bodied, e.g. Laser-Flex) ETT; FiO₂ ≤ 0.30 in air (no N₂O); cuff filled with saline ± methylene blue; wet pledgets around the cuff; surgeon to use lowest effective laser power; have saline and a spare circuit ready.",
    answer:
      "Decline the original plan. Use a laser-resistant ETT, run FiO₂ ≤ 0.30 in air with N₂O omitted, fill the cuff with saline + dye, and brief the team on the airway-fire drill (stop O₂, remove tube, flood with saline, mask-ventilate, re-intubate, bronchoscopy).",
  },
  {
    title: "Numerical aperture of a fibreoptic bronchoscope",
    scenario:
      "A coherent fibre bundle uses a glass core (n₁ = 1.62) and cladding (n₂ = 1.52). Calculate the numerical aperture and the maximum acceptance half-angle in air.",
    working:
      "NA = √(n₁² − n₂²) = √(1.62² − 1.52²) = √(2.6244 − 2.3104) = √0.314 ≈ 0.56.\nNA = n₀ sin θ_max with n₀ (air) = 1 → sin θ_max = 0.56 → θ_max ≈ 34°.\nCritical angle inside the fibre: sin θc = n₂/n₁ = 1.52/1.62 = 0.938 → θc ≈ 69.8° (measured from the normal).",
    answer:
      "NA ≈ 0.56, giving an acceptance half-angle of ~34° in air. Light entering within this cone undergoes total internal reflection (above the 69.8° critical angle) and propagates with negligible loss along the fibre.",
  },
];

const LaserFibreopticsTopic = () => {
  return (
    <TopicTemplate
      title="Lasers & Fibreoptics"
      subtitle="LASER principles, fibreoptic light transmission, total internal reflection, and clinical applications"
      backPath="/physics"
      backLabel="Physics"
      accentColor="text-physics"
      topicId="lasers-fibreoptics"
      topicTitle="Lasers & Fibreoptics"
      objectives={objectives}
      workedExamples={workedExamples}
      quizQuestions={laserFibreopticsQuiz}
      sectionExamMapping={{
        objectives: { exams: [Exam.PRIMARY, Exam.FINAL], curriculumCodes: ["RCoA Primary — Physics", "RCoA Final — Physics"] },
        workedExamples: { exams: [Exam.PRIMARY, Exam.FINAL] },
        keyPoints: { exams: [Exam.PRIMARY, Exam.FINAL] },
      }}
      sectionSources={{
        workedExamples: ["BJA Educ 2004"],
      }}
      keyPoints={[
        "LASER = Light Amplification by Stimulated Emission of Radiation — requires population inversion in a gain medium",
        "Laser light is monochromatic (single wavelength), coherent (waves in phase), and collimated (parallel beam)",
        "CO₂ laser (10,600 nm) is absorbed by water and cuts tissue; it ignites PVC ETTs — use laser-safe tubes with saline-filled cuffs",
        "Total internal reflection occurs when light travels from high to low refractive index at angle > critical angle (sin θc = n₂/n₁)",
        "Coherent fibre bundles transmit images (fibres maintain spatial position); incoherent bundles transmit light only",
        "Numerical aperture NA = √(n₁² − n₂²) defines the acceptance cone angle of the fibre",
        "Reduce FiO₂ to ≤30% during airway laser surgery; avoid N₂O as it supports combustion",
      ]}
      coreConcepts={
        <>
          <ExamSection id="introduction" exams={[Exam.PRIMARY, Exam.FINAL]}>
            <h2 className="text-xl font-bold text-foreground mb-2">Introduction</h2>
            <p className="text-muted-foreground leading-relaxed">
              Lasers and fibreoptics are fundamental to modern anaesthetic and surgical practice. Understanding laser physics is
              essential for safe airway laser surgery, while fibreoptic principles underpin the fibreoptic bronchoscope — a
              cornerstone of difficult airway management. Both topics appear regularly in the Primary FRCA physics examination.
            </p>
          </ExamSection>

          <ExamSection id="diagram" exams={[Exam.PRIMARY, Exam.FINAL]}>
            <h2 className="text-xl font-bold text-foreground mb-4">Interactive Diagrams</h2>
            <LaserFibreopticsDiagram />
          </ExamSection>

          <ExamSection id="laser-physics" exams={[Exam.PRIMARY, Exam.FINAL]}>
            <h2 className="text-xl font-bold text-foreground mb-2">LASER Physics</h2>
            <div className="text-muted-foreground leading-relaxed space-y-3">
              <p>
                A laser produces light through <strong>stimulated emission</strong>. An incoming photon interacts with an atom in an
                excited (metastable) state, causing it to emit an identical photon — same wavelength, phase, and direction. This
                requires <strong>population inversion</strong>: more atoms must be in the excited state than the ground state, achieved
                by external energy input (pumping) — optical, electrical, or chemical.
              </p>
              <p>
                The gain medium sits within an <strong>optical cavity</strong> bounded by two mirrors. The total mirror reflects all
                light back; the partial mirror allows a fraction to escape as the laser beam. Multiple passes through the gain medium
                amplify the light exponentially. The resulting beam is <strong>monochromatic</strong> (single wavelength),
                <strong> coherent</strong> (waves in phase), and <strong>collimated</strong> (parallel, minimal divergence).
              </p>
              <p>
                <strong>CO₂ laser</strong> (10,600 nm, far infrared): strongly absorbed by water → precise cutting and vaporisation.
                Used extensively in airway surgery. <strong>Nd:YAG</strong> (1,064 nm, near infrared): penetrates deeply into tissue,
                good for coagulation. Can be transmitted via fibreoptic. <strong>KTP</strong> (532 nm, green): frequency-doubled
                Nd:YAG, absorbed by haemoglobin, used for superficial vascular lesions and vocal cord surgery.
              </p>
            </div>
          </ExamSection>

          <ExamSection id="fibreoptics" exams={[Exam.PRIMARY, Exam.FINAL]}>
            <h2 className="text-xl font-bold text-foreground mb-2">Fibreoptics & Total Internal Reflection</h2>
            <div className="text-muted-foreground leading-relaxed space-y-3">
              <p>
                <strong>Total internal reflection (TIR)</strong> occurs when light travelling from a medium of higher refractive index
                (n₁, core) to one of lower refractive index (n₂, cladding) strikes the interface at an angle greater than the
                <strong> critical angle</strong>: sin θc = n₂/n₁. All light is reflected back into the core with zero transmission loss.
              </p>
              <p>
                The <strong>numerical aperture (NA)</strong> of a fibre defines the cone of light it can accept: NA = √(n₁² − n₂²).
                A larger NA accepts more light but provides lower image resolution. Clinical fibreoptic bundles contain thousands of
                individual fibres, each 8–12 μm in diameter.
              </p>
              <p>
                <strong>Coherent bundles</strong> maintain the spatial arrangement of fibres from one end to the other, allowing image
                transmission (viewing channel of bronchoscope). <strong>Incoherent bundles</strong> have random fibre arrangement and
                transmit light only (illumination channel). Modern video bronchoscopes use a CCD chip at the tip instead of a coherent
                bundle, providing superior image quality.
              </p>
            </div>
          </ExamSection>

          <ExamSection id="laser-safety" exams={[Exam.PRIMARY, Exam.FINAL]}>
            <h2 className="text-xl font-bold text-foreground mb-2">Laser Safety in Anaesthesia</h2>
            <div className="text-muted-foreground leading-relaxed space-y-3">
              <p>
                <strong>Airway fire</strong> is the most feared complication of airway laser surgery. The CO₂ laser can ignite standard
                PVC or rubber endotracheal tubes. Prevention requires: laser-safe tubes (metal shaft, e.g., Laser-Flex), reducing FiO₂
                to ≤30%, avoiding N₂O (supports combustion), filling the cuff with saline (± methylene blue dye as a leak indicator),
                and protecting the cuff with wet pledgets.
              </p>
              <p>
                <strong>Eye protection</strong> is mandatory for all theatre personnel. The goggles must be specific to the laser
                wavelength in use (CO₂ goggles do not protect against Nd:YAG). The patient's eyes are taped shut and covered with wet
                gauze. Warning signs must be displayed on all theatre doors, and the laser should be key-operated with a designated
                laser safety officer.
              </p>
            </div>
          </ExamSection>
          <ExamPitfallsCallout
            accent="physics"
            pitfalls={[
              "LASER = Light Amplification by Stimulated Emission of Radiation — needs a population inversion in an active medium.",
              "CO₂ laser (10.6 µm) cuts and is absorbed by water; Nd:YAG (1.064 µm) penetrates deeper; KTP (532 nm) is absorbed by haemoglobin.",
              "Airway laser safety: FiO₂ <30%, no N₂O, laser-resistant tube, saline-filled cuff, wet swabs, eye protection for all in room.",
              "Class 4 lasers require controlled environment, warning signs, key-switch and a designated laser safety officer.",
              "Fibreoptics rely on total internal reflection within a higher-index core; coherent bundles transmit images, non-coherent bundles transmit light only.",
            ]}
          />
        </>
      }
    />
  );
};

export default LaserFibreopticsTopic;
