import { Link } from "react-router-dom";
import { NoteLayout } from "./NoteLayout";
import { HeartSoundsEcgDiagram } from "@/components/diagrams/physiology/HeartSoundsEcgDiagram";

/**
 * Companion note to /notes/wiggers-diagram-explained.
 *
 * Where the Wiggers note explains the pressure/volume traces, this one
 * isolates the auscultatory and electrical timing that examiners ask
 * about: which sound belongs to which valve event, which murmur occupies
 * which part of the cycle, and how the ECG changes track with them.
 */
const HeartSoundsEcgNote = () => (
  <NoteLayout
    slug="heart-sounds-ecg-cardiac-cycle"
    title="Heart sounds and the ECG in the cardiac cycle"
    shortTitle="Heart sounds and the ECG"
    description="Interactive guide to S1–S4, added sounds and murmurs timed against the ECG and the cardiac cycle, with the exam-relevant findings in AS, MR, MS, AF and heart block."
    datePublished="2026-08-04"
    lede="Every heart sound is a pressure crossing and every murmur is a pressure gradient. Line them up against the ECG and the phases of the Wiggers diagram, and auscultation becomes deduction rather than recall."
    examTags={["primary", "final", "fficm"]}
    curriculumCodes={["CP_BK_02", "PR_BK_15"]}
    faqs={[
      {
        q: "What causes the first and second heart sounds?",
        a: "S1 is closure of the mitral then tricuspid valves at the onset of isovolumetric contraction, when ventricular pressure rises above atrial pressure. S2 is closure of the aortic then pulmonary valves at the onset of isovolumetric relaxation, when ventricular pressure falls below arterial pressure. The sound is produced by abrupt deceleration of blood and vibration of the valve leaflets and surrounding structures, not by the leaflets striking one another.",
      },
      {
        q: "Where do S1 and S2 fall on the ECG?",
        a: "S1 follows the QRS complex by roughly 20–40 ms, because electrical depolarisation must precede mechanical contraction. S2 falls at the end of the T wave, as repolarisation completes and ejection ends. An S4, when present, is coincident with the P wave, since it is generated by atrial contraction.",
      },
      {
        q: "What is the difference between S3 and S4?",
        a: "S3 occurs in early diastole, 0.12–0.18 s after S2, during rapid passive filling — it reflects a dilated, volume-loaded ventricle and can be physiological under 40 years or in pregnancy. S4 occurs in late diastole immediately before S1 and reflects forceful atrial contraction into a stiff, non-compliant ventricle; it is always pathological in adults and cannot occur in atrial fibrillation.",
      },
      {
        q: "How do you distinguish an ejection systolic from a pansystolic murmur?",
        a: "An ejection systolic (crescendo–decrescendo) murmur such as aortic stenosis starts after S1 — flow only becomes turbulent once the aortic valve opens — and finishes before S2. A pansystolic murmur such as mitral regurgitation occupies the whole of systole and obscures both S1 and S2, because the ventriculo-atrial pressure gradient exists from mitral closure until it reopens.",
      },
      {
        q: "Why does S2 split on inspiration?",
        a: "Inspiration lowers intrathoracic pressure, increasing systemic venous return and right ventricular ejection time, which delays pulmonary valve closure (P2). Simultaneously pulmonary vascular capacitance rises and left ventricular filling falls, shortening left ventricular ejection and advancing aortic closure (A2). The split therefore widens on inspiration and narrows on expiration.",
      },
      {
        q: "Which ECG findings accompany the classic valve lesions?",
        a: "Aortic stenosis: left ventricular hypertrophy by voltage criteria, left axis deviation, and conduction block from calcific extension into the septum. Mitral stenosis: P mitrale then atrial fibrillation, with right ventricular hypertrophy if pulmonary hypertension develops. Mitral regurgitation: left atrial enlargement and atrial fibrillation with left ventricular volume overload.",
      },
      {
        q: "Why is atrial fibrillation badly tolerated in aortic and mitral stenosis?",
        a: "Loss of organised atrial contraction removes the atrial kick, which contributes up to 25% of stroke volume and matters most when ventricular filling is already impaired. The associated tachycardia shortens diastole disproportionately, reducing both filling time and — for the hypertrophied left ventricle — coronary perfusion time.",
      },
    ]}
    related={[
      { label: "Wiggers diagram explained: pressures, ECG and heart sounds", to: "/notes/wiggers-diagram-explained" },
      { label: "Cardiac cycle (Physiology)", to: "/physiology/cardiac-cycle" },
      { label: "Cardiac output formula: Fick, thermodilution and CO = SV × HR", to: "/notes/cardiac-output-formula" },
    ]}
  >
    <p>
      The{" "}
      <Link to="/notes/wiggers-diagram-explained">Wiggers diagram</Link>{" "}
      shows why valves open and close: they follow pressure gradients. This
      guide takes the two lower traces of that diagram — the ECG and the
      phonocardiogram — and works through the findings the FRCA and FFICM
      examiners actually ask for.
    </p>

    <h2>Interactive: sounds, murmurs and the ECG</h2>
    <p>
      Choose a scenario to redraw the ECG and the auscultatory timeline on a
      shared cycle axis, then select any sound marker for its mechanism.
    </p>

    <HeartSoundsEcgDiagram />

    <h2>The four sounds and their pressure events</h2>
    <ul>
      <li>
        <strong>S1 — mitral then tricuspid closure.</strong> Marks the start
        of isovolumetric contraction, ~20–40 ms after the QRS. Its loudness
        depends on how far apart the leaflets are when the ventricle
        contracts: loud in mitral stenosis and short PR intervals, soft in
        mitral regurgitation and long PR intervals, variable in atrial
        fibrillation and complete heart block.
      </li>
      <li>
        <strong>S2 — aortic (A2) then pulmonary (P2) closure.</strong> Marks
        the start of isovolumetric relaxation and produces the dicrotic notch
        on the arterial trace. Splitting is physiological on inspiration.
      </li>
      <li>
        <strong>S3 — early diastole,</strong> during rapid passive filling,
        just after mitral opening and the y descent. Volume overload.
      </li>
      <li>
        <strong>S4 — late diastole,</strong> coincident with the P wave and
        the a wave. Pressure overload and a stiff ventricle.
      </li>
    </ul>

    <h2>Timing rules that decide the murmur</h2>
    <p>
      Two questions settle almost every murmur in a viva. First,{" "}
      <strong>is the gradient present during systole or diastole?</strong>{" "}
      Systolic murmurs come from flow out of a ventricle (aortic or pulmonary
      stenosis) or backwards out of a ventricle (mitral or tricuspid
      regurgitation, VSD). Diastolic murmurs come from flow into a ventricle
      (mitral or tricuspid stenosis) or backwards into one (aortic or
      pulmonary regurgitation). Second,{" "}
      <strong>does the murmur begin at the sound or after it?</strong> A
      murmur that starts with S1 and runs into S2 is regurgitant and
      pansystolic; one that starts after S1 and stops before S2 has to wait
      for a valve to open, so it is an ejection murmur.
    </p>

    <h2>ECG changes that travel with the lesion</h2>
    <ul>
      <li>
        <strong>Aortic stenosis:</strong> LVH by voltage criteria with strain
        pattern; left axis deviation; AV or bundle branch block if calcium
        extends into the septum. An S4 usually accompanies it.
      </li>
      <li>
        <strong>Mitral stenosis:</strong> P mitrale (broad, bifid P wave in
        lead II), then atrial fibrillation; RVH and right axis deviation once
        pulmonary hypertension develops.
      </li>
      <li>
        <strong>Mitral regurgitation:</strong> left atrial enlargement, atrial
        fibrillation, and LV volume-overload changes rather than the
        pressure-overload pattern of stenosis.
      </li>
      <li>
        <strong>Complete heart block:</strong> dissociated P waves and a slow,
        often broad escape rhythm; the clinical corollaries are variable S1
        and irregular cannon a waves in the JVP.
      </li>
    </ul>

    <h2>Summary</h2>
    <ul>
      <li>
        S1 = AV valve closure, start of systole, just after the QRS. S2 = 
        semilunar valve closure, end of systole, at the end of the T wave.
      </li>
      <li>
        S3 is an early-diastolic filling sound (volume overload); S4 is a
        presystolic atrial sound (pressure overload) and is impossible in AF.
      </li>
      <li>
        Ejection systolic murmurs start after S1 and finish before S2;
        pansystolic murmurs fill systole and bury both sounds.
      </li>
      <li>
        A short A2–opening snap interval, a soft or absent A2 and a
        late-peaking murmur are all severity markers.
      </li>
      <li>
        Losing the atrial kick removes the P wave, the a wave and S4 together,
        and is worst tolerated where filling is already limited.
      </li>
      <li>
        Tachycardia shortens diastole preferentially — filling time and left
        ventricular coronary perfusion time fall first.
      </li>
    </ul>
  </NoteLayout>
);

export default HeartSoundsEcgNote;
