// AUTO-GENERATED by scripts/generate-diagram-snapshot-registry.mjs
// Do not edit by hand. Re-run `npm run gen:diagram-snapshots`.
/* eslint-disable @typescript-eslint/no-explicit-any */
import { lazy, type LazyExoticComponent, type ComponentType } from "react";

// Registry intentionally typed as ComponentType<any>: many diagrams
// require props, and the sandbox route mounts them with none. Those
// will throw at render time and be caught by the route's error
// boundary, which causes the Playwright spec to skip that diagram.
export const diagramSnapshotRegistry: Record<string, LazyExoticComponent<ComponentType<any>>> = {
};

export const diagramSnapshotNames = Object.keys(diagramSnapshotRegistry);
