/**
 * AUTO-GENERATED by `npm run gen:citation-allowlist`.
 * Edit by lowering numbers (or removing rows) as you backfill citations.
 * The test fails if a file's actual uncited count EXCEEDS the value here.
 */
export interface AllowlistEntry {
  file: string;
  uncitedKeyPoints: number;
  uncitedWorkedExamples: number;
}

export const CITATION_ALLOWLIST: AllowlistEntry[] = [

];
