/**
 * citation-coverage.test.ts
 *
 * Fails the build when:
 *   - A NEW key point or worked example is added without `cites: [...]`, or
 *   - An existing `cites` label doesn't exist in `topicReferences[topicId]`,
 *     or
 *   - A file in the allowlist has FEWER uncited entries than recorded
 *     (means it was migrated — remove it from the allowlist).
 *
 * To regenerate the allowlist after intentionally migrating files, run:
 *   npm run gen:citation-allowlist
 *
 * The allowlist lives at src/__tests__/citation-coverage-allowlist.ts so
 * it is part of the source tree and reviewable in diffs.
 */
import { describe, it, expect } from "vitest";
import { readdirSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";
import { topicReferences } from "@/data/references";
import { extractTopic, type ExtractedEntry } from "./citation-coverage-extractor";
import { CITATION_ALLOWLIST } from "./citation-coverage-allowlist";

const REPO_ROOT = resolve(__dirname, "../..");
const TOPICS_DIR = resolve(__dirname, "../pages/topics");

function listTopicFiles(): string[] {
  return readdirSync(TOPICS_DIR)
    .filter((f) => f.endsWith(".tsx"))
    .map((f) => join(TOPICS_DIR, f));
}

interface FileReport {
  rel: string;
  topicId: string | null;
  uncitedKeyPoints: ExtractedEntry[];
  uncitedWorkedExamples: ExtractedEntry[];
  invalidCitations: { entry: ExtractedEntry; badLabel: string }[];
  warnings: string[];
}

function analyzeFile(file: string): FileReport {
  const t = extractTopic(file);
  const rel = relative(REPO_ROOT, file);
  const refs = (t.topicId && topicReferences[t.topicId]) || [];
  const knownLabels = new Set(refs.map((r) => r.label));

  const isUncited = (e: ExtractedEntry) =>
    !e.unresolved && (!e.hasCitesProperty || e.cites.length === 0);

  const invalidCitations: FileReport["invalidCitations"] = [];
  for (const entry of [...t.keyPoints, ...t.workedExamples]) {
    for (const label of entry.cites) {
      if (!knownLabels.has(label)) {
        invalidCitations.push({ entry, badLabel: label });
      }
    }
  }

  return {
    rel,
    topicId: t.topicId,
    uncitedKeyPoints: t.keyPoints.filter(isUncited),
    uncitedWorkedExamples: t.workedExamples.filter(isUncited),
    invalidCitations,
    warnings: t.warnings,
  };
}

// ---------------------------------------------------------------------------
// One-shot allowlist generator: `WRITE_CITATION_ALLOWLIST=1 vitest run citation`
// ---------------------------------------------------------------------------
if (process.env.WRITE_CITATION_ALLOWLIST === "1") {
  const reports = listTopicFiles().map(analyzeFile);
  const lines = reports
    .filter(
      (r) =>
        r.uncitedKeyPoints.length > 0 || r.uncitedWorkedExamples.length > 0,
    )
    .sort((a, b) => a.rel.localeCompare(b.rel))
    .map(
      (r) =>
        `  { file: "${r.rel}", uncitedKeyPoints: ${r.uncitedKeyPoints.length}, uncitedWorkedExamples: ${r.uncitedWorkedExamples.length} },`,
    );

  const out = `/**
 * AUTO-GENERATED by \`npm run gen:citation-allowlist\`.
 * Edit by lowering numbers (or removing rows) as you backfill citations.
 * The test fails if a file's actual uncited count EXCEEDS the value here.
 */
export interface AllowlistEntry {
  file: string;
  uncitedKeyPoints: number;
  uncitedWorkedExamples: number;
}

export const CITATION_ALLOWLIST: AllowlistEntry[] = [
${lines.join("\n")}
];
`;
  const target = resolve(__dirname, "citation-coverage-allowlist.ts");
  writeFileSync(target, out);
  // eslint-disable-next-line no-console
  console.log(
    `[gen:citation-allowlist] wrote ${lines.length} entries to ${relative(
      REPO_ROOT,
      target,
    )}`,
  );
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------
const allowMap = new Map(CITATION_ALLOWLIST.map((e) => [e.file, e]));

describe("citation coverage", () => {
  const reports = listTopicFiles().map(analyzeFile);

  it("every cite label resolves to a real reference in topicReferences[topicId]", () => {
    const errors: string[] = [];
    for (const r of reports) {
      for (const { entry, badLabel } of r.invalidCitations) {
        errors.push(
          `${r.rel}:${entry.line}  ${entry.kind} #${entry.index} ("${entry.preview}") cites unknown label "${badLabel}" — topicId="${r.topicId}". Add it to topicReferences in src/data/references.ts, or fix the typo.`,
        );
      }
    }
    expect(errors, errors.join("\n")).toEqual([]);
  });

  it("no NEW uncited keyPoints or workedExamples beyond the allowlist", () => {
    const errors: string[] = [];

    for (const r of reports) {
      const allowed = allowMap.get(r.rel);
      const actualKp = r.uncitedKeyPoints.length;
      const actualWx = r.uncitedWorkedExamples.length;

      if (allowed) {
        if (actualKp > allowed.uncitedKeyPoints) {
          errors.push(
            `${r.rel}: ${actualKp} uncited keyPoints (allowlist permits ${allowed.uncitedKeyPoints}). New uncited entries are not allowed.`,
          );
        }
        if (actualWx > allowed.uncitedWorkedExamples) {
          errors.push(
            `${r.rel}: ${actualWx} uncited workedExamples (allowlist permits ${allowed.uncitedWorkedExamples}). New uncited entries are not allowed.`,
          );
        }
        if (
          actualKp < allowed.uncitedKeyPoints ||
          actualWx < allowed.uncitedWorkedExamples
        ) {
          errors.push(
            `${r.rel}: improved! Now ${actualKp} uncited keyPoints + ${actualWx} uncited workedExamples (was ${allowed.uncitedKeyPoints} + ${allowed.uncitedWorkedExamples}). Lower the numbers (or delete the row) in src/__tests__/citation-coverage-allowlist.ts. Run \`npm run gen:citation-allowlist\` to regenerate.`,
          );
        }
      } else {
        // Not in allowlist — strict mode applies.
        for (const e of r.uncitedKeyPoints) {
          errors.push(
            `${r.rel}:${e.line}  keyPoint #${e.index} ("${e.preview}") has no citation. Add a \`cites: ["Label"]\` field that matches an entry in topicReferences["${r.topicId}"].`,
          );
        }
        for (const e of r.uncitedWorkedExamples) {
          errors.push(
            `${r.rel}:${e.line}  workedExample #${e.index} ("${e.preview}") has no citation. Add \`cites: ["Label"]\` to the example object.`,
          );
        }
      }
    }

    expect(errors, errors.join("\n")).toEqual([]);
  });

  it("allowlist has no stale entries (every listed file still exists)", () => {
    const live = new Set(reports.map((r) => r.rel));
    const stale = CITATION_ALLOWLIST.filter((e) => !live.has(e.file));
    expect(
      stale,
      `Stale allowlist entries — these files no longer exist:\n${stale
        .map((e) => "  " + e.file)
        .join("\n")}`,
    ).toEqual([]);
  });
});
