import { test, expect } from "@playwright/test";
import { readFileSync } from "node:fs";
import { join } from "node:path";

/**
 * Visual snapshot regression suite for every interactive diagram.
 *
 * The list of diagrams is generated by
 * `scripts/generate-diagram-snapshot-registry.mjs` (run pre-dev/pre-build)
 * and consumed here as a static JSON manifest so the test list stays in
 * sync with the registry without bundling React into the spec.
 *
 * Each diagram is mounted in isolation at /dev/diagram-snapshot/:name
 * with animations frozen via the route's injected stylesheet. Diagrams
 * that throw when mounted with no props are auto-skipped (they need
 * required props and can't render standalone).
 *
 * Baselines are committed under tests/visual/diagram-snapshots.spec.ts-
 * snapshots/. To refresh after an intentional visual change run:
 *
 *   npx playwright test tests/visual/diagram-snapshots.spec.ts \
 *     --update-snapshots
 */

type Manifest = {
  generatedAt: string;
  count: number;
  diagrams: { name: string; route: string }[];
};

const manifest: Manifest = JSON.parse(
  readFileSync(
    join(__dirname, "__diagram-snapshot-manifest.generated.json"),
    "utf8",
  ),
);

test.describe("diagram visual snapshots", () => {
  test.use({ viewport: { width: 1024, height: 768 } });

  for (const { name, route } of manifest.diagrams) {
    test(`${name} matches baseline`, async ({ page }) => {
      const consoleErrors: string[] = [];
      page.on("pageerror", (e) => consoleErrors.push(e.message));

      await page.goto(route, { waitUntil: "domcontentloaded" });

      // Wait for either ready or error status from the sandbox.
      await page.waitForFunction(
        () => {
          const s = document.body.dataset.snapshotStatus;
          return (
            s === "ready" || s === "error" || !!document.querySelector("[data-snapshot-error]")
          );
        },
        { timeout: 15_000 },
      );

      const status = await page.evaluate(
        () => document.body.dataset.snapshotStatus,
      );
      const errored = await page
        .locator("[data-snapshot-error]")
        .count()
        .then((c) => c > 0);

      if (status === "error" || errored) {
        test.skip(true, `${name}: requires props or threw on mount`);
        return;
      }

      // Confirm body signals ready (RAFs settled) before the screenshot.
      await page.waitForFunction(
        () => document.body.dataset.snapshotReady === "true",
        { timeout: 5_000 },
      );

      const target = page.locator("[data-snapshot-target]");
      await expect(target).toHaveScreenshot(`${name}.png`, {
        animations: "disabled",
        maxDiffPixelRatio: 0.01,
      });
    });
  }
});
