#!/usr/bin/env python3
"""
Plate signature/artifact scanner.

Scans every JPEG in src/assets/plates/ and flags:
  - Known artist signatures or copyright marks (Netter, Gray, etc.)
  - Generic AI-watermark phrases ("generated by", "openai", "midjourney"…)
  - Faint corner text (likely signatures) — even when OCR can't read them,
    we look for a high-contrast cluster of small pixels in the bottom corners.

Exits non-zero if anything is flagged so it can gate publishing in CI.

Usage:
    python scripts/check-plate-artifacts.py
    python scripts/check-plate-artifacts.py --json
    python scripts/check-plate-artifacts.py path/to/plate.jpg
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable

from PIL import Image, ImageFilter, ImageOps

# Patterns that should NEVER appear in a plate (case-insensitive substring).
FORBIDDEN_PATTERNS: list[tuple[str, str]] = [
    (r"\bnetter\b", "Netter signature/copyright"),
    (r"\bf\.?\s*netter\b", "Netter signature/copyright"),
    (r"\bm\.?\s*d\.?\b", "'M.D.' suffix (likely artist signature)"),
    (r"\bgray'?s\b", "Gray's Anatomy attribution"),
    (r"\bgrant'?s\b", "Grant's Atlas attribution"),
    (r"\bcopyright\b", "copyright text"),
    (r"©", "copyright symbol"),
    (r"\bmidjourney\b", "Midjourney watermark"),
    (r"\bopenai\b", "OpenAI watermark"),
    (r"\bdall[\-\s]?e\b", "DALL-E watermark"),
    (r"\bstable\s*diffusion\b", "Stable Diffusion watermark"),
    (r"\bgenerated\s+by\b", "AI generation watermark"),
    (r"\bgetty\b", "Getty Images watermark"),
    (r"\bshutterstock\b", "Shutterstock watermark"),
    (r"\balamy\b", "Alamy watermark"),
    (r"\bwatermark\b", "literal 'watermark' text"),
    (r"\bsample\b", "literal 'sample' text"),
]

# Corner crop fraction (signatures usually live in the outer 18%)
CORNER_FRAC = 0.22
# Minimum dark-pixel cluster size to call a corner "suspicious"
SUSPICIOUS_PIXEL_RATIO = 0.004  # 0.4% of corner pixels
# Skip suspicious-pixel check if this many dark pixels exist (corner is
# legitimately part of the drawing, not a signature).
DENSE_DRAWING_RATIO = 0.06


@dataclass
class Finding:
    plate: str
    severity: str  # "error" | "warning"
    code: str
    message: str
    detail: str = ""


@dataclass
class PlateReport:
    plate: str
    ocr_text: str = ""
    findings: list[Finding] = field(default_factory=list)


def run_tesseract(image_path: Path) -> str:
    """Run tesseract; return raw text. Empty string on failure."""
    try:
        # Pre-process: upscale + threshold to make faint text legible.
        img = Image.open(image_path).convert("L")
        # Upscale 2× to help read tiny signatures
        img = img.resize((img.width * 2, img.height * 2), Image.LANCZOS)
        # Auto-contrast + sharpen
        img = ImageOps.autocontrast(img, cutoff=2)
        img = img.filter(ImageFilter.SHARPEN)
        tmp = Path("/tmp") / f"_ocr_{image_path.stem}.png"
        img.save(tmp)
        result = subprocess.run(
            ["tesseract", str(tmp), "-", "--psm", "11", "-l", "eng"],
            capture_output=True,
            text=True,
            timeout=30,
        )
        try:
            tmp.unlink()
        except OSError:
            pass
        if result.returncode != 0:
            return ""
        return result.stdout
    except Exception as exc:  # pragma: no cover
        print(f"  ! tesseract failed on {image_path.name}: {exc}", file=sys.stderr)
        return ""


def scan_corner(img: Image.Image, corner: str) -> tuple[float, float]:
    """Return (dark_ratio, mid_ratio) for a corner crop.

    dark_ratio = fraction of near-black pixels (likely ink)
    mid_ratio  = fraction of mid-tone pixels (likely actual drawing)
    """
    w, h = img.size
    cw, ch = int(w * CORNER_FRAC), int(h * CORNER_FRAC)
    boxes = {
        "tl": (0, 0, cw, ch),
        "tr": (w - cw, 0, w, ch),
        "bl": (0, h - ch, cw, h),
        "br": (w - cw, h - ch, w, h),
    }
    crop = img.crop(boxes[corner]).convert("L")
    pixels = list(crop.getdata())
    total = len(pixels)
    dark = sum(1 for p in pixels if p < 60)
    mid = sum(1 for p in pixels if 60 <= p < 200)
    return dark / total, mid / total


def check_corners(image_path: Path) -> list[Finding]:
    findings: list[Finding] = []
    img = Image.open(image_path)
    for corner in ("tl", "tr", "bl", "br"):
        dark, mid = scan_corner(img, corner)
        # If the corner has a small but non-zero dark pixel cluster on a mostly
        # empty background, that's the signature pattern.
        if SUSPICIOUS_PIXEL_RATIO <= dark <= DENSE_DRAWING_RATIO and mid < 0.15:
            findings.append(
                Finding(
                    plate=image_path.name,
                    severity="warning",
                    code="suspicious-corner",
                    message=f"Possible signature/watermark in {corner.upper()} corner",
                    detail=f"dark_ratio={dark:.3%}, mid_ratio={mid:.3%}",
                )
            )
    return findings


def check_text(image_path: Path) -> tuple[str, list[Finding]]:
    text = run_tesseract(image_path)
    findings: list[Finding] = []
    if not text.strip():
        return text, findings
    haystack = text.lower()
    for pattern, label in FORBIDDEN_PATTERNS:
        m = re.search(pattern, haystack, flags=re.IGNORECASE)
        if m:
            # Pull a short context window
            start = max(0, m.start() - 20)
            end = min(len(text), m.end() + 20)
            context = text[start:end].replace("\n", " ").strip()
            findings.append(
                Finding(
                    plate=image_path.name,
                    severity="error",
                    code="forbidden-text",
                    message=label,
                    detail=f"matched '{m.group(0)}' near: …{context}…",
                )
            )
    return text, findings


def scan_plate(image_path: Path) -> PlateReport:
    report = PlateReport(plate=image_path.name)
    text, text_findings = check_text(image_path)
    report.ocr_text = text
    report.findings.extend(text_findings)
    report.findings.extend(check_corners(image_path))
    return report


def iter_plates(roots: Iterable[Path]) -> Iterable[Path]:
    for root in roots:
        if root.is_file():
            yield root
            continue
        if not root.is_dir():
            continue
        for p in sorted(root.iterdir()):
            if p.suffix.lower() in {".jpg", ".jpeg", ".png", ".webp"}:
                yield p


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("paths", nargs="*", help="Files or directories (default: src/assets/plates/)")
    ap.add_argument("--json", action="store_true", help="Emit JSON report")
    ap.add_argument("--quiet", action="store_true", help="Only print findings")
    args = ap.parse_args()

    if args.paths:
        targets = [Path(p) for p in args.paths]
    else:
        targets = [Path("src/assets/plates")]

    reports: list[PlateReport] = []
    for image_path in iter_plates(targets):
        if not args.quiet:
            print(f"scanning {image_path}…")
        reports.append(scan_plate(image_path))

    errors = [f for r in reports for f in r.findings if f.severity == "error"]
    warnings = [f for r in reports for f in r.findings if f.severity == "warning"]

    if args.json:
        print(json.dumps(
            {
                "scanned": len(reports),
                "errors": [f.__dict__ for f in errors],
                "warnings": [f.__dict__ for f in warnings],
            },
            indent=2,
        ))
    else:
        print(f"\nScanned {len(reports)} plate(s); {len(errors)} error(s), {len(warnings)} warning(s).")
        for f in errors + warnings:
            sev = "ERROR" if f.severity == "error" else "warn "
            print(f"  [{sev}] {f.plate}: {f.message}")
            if f.detail:
                print(f"          {f.detail}")

    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
